import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/ui/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#4de082",
        "outline": "#869486",
        "on-secondary-container": "#004d44",
        "inverse-surface": "#e0e4dc",
        "on-primary-fixed-variant": "#005227",
        "on-error": "#690005",
        "on-primary-container": "#005e2d",
        "surface-container": "#1d211c",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary": "#003824",
        "surface-container-low": "#191d18",
        "primary-fixed-dim": "#4de082",
        "on-secondary-fixed-variant": "#005047",
        "outline-variant": "#3d4a3e",
        "primary-fixed": "#6dfe9c",
        "on-primary": "#003919",
        "secondary-fixed": "#62fae3",
        "error": "#ffb4ab",
        "on-secondary": "#003731",
        "surface-container-high": "#272b26",
        "primary": "#6bfb9a",
        "on-tertiary-container": "#005d3f",
        "inverse-primary": "#006d36",
        "surface": "#101410",
        "on-background": "#e0e4dc",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#bccabb",
        "secondary-container": "#03c6b2",
        "tertiary-container": "#4bdca1",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-lowest": "#0b0f0b",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#002113",
        "surface-variant": "#323631",
        "inverse-on-surface": "#2d312c",
        "on-surface": "#e0e4dc",
        "on-primary-fixed": "#00210c",
        "tertiary": "#6cf9bb",
        "secondary": "#44e2cd",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-highest": "#323631",
        "secondary-fixed-dim": "#3cddc7",
        "on-secondary-fixed": "#00201c",
        "primary-container": "#4ade80",
        "background": "#101410",
        "surface-bright": "#363a35",
        "surface-dim": "#101410",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "container-max": "1200px",
        "unit": "8px",
      },
      fontFamily: {
        "headline-md": ["var(--font-bricolage)"],
        "label-caps": ["var(--font-jetbrains)"],
        "body-md": ["var(--font-hanken)"],
        "display-lg": ["var(--font-bricolage)"],
        "technical-sm": ["var(--font-jetbrains)"],
        "body-lg": ["var(--font-hanken)"],
        "display-lg-mobile": ["var(--font-bricolage)"],
      },
      fontSize: {
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "label-caps": [
          "11px",
          { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" },
        ],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": [
          "64px",
          {
            lineHeight: "72px",
            letterSpacing: "-0.02em",
            fontWeight: "800",
          },
        ],
        "technical-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg-mobile": [
          "36px",
          {
            lineHeight: "44px",
            letterSpacing: "-0.02em",
            fontWeight: "800",
          },
        ],
      },
    },
  },
  plugins: [],
};
export default config;
