import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/ui/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#49cae4",
        "outline": "#8c8790",
        "on-secondary-container": "#262427",
        "inverse-surface": "#fcfcfa",
        "on-primary-fixed-variant": "#153f48",
        "on-error": "#690005",
        "on-primary-container": "#101112",
        "surface-container": "#2f2c31",
        "tertiary-fixed-dim": "#d9d7d4",
        "on-tertiary": "#262427",
        "surface-container-low": "#28262a",
        "primary-fixed-dim": "#49cae4",
        "on-secondary-fixed-variant": "#5c4613",
        "outline-variant": "#4b4750",
        "primary-fixed": "#8ee8fa",
        "on-primary": "#101112",
        "secondary-fixed": "#ffdc8f",
        "error": "#ffb4ab",
        "on-secondary": "#262427",
        "surface-container-high": "#37333a",
        "primary": "#49cae4",
        "on-tertiary-container": "#262427",
        "inverse-primary": "#167f94",
        "surface": "#262427",
        "on-background": "#fcfcfa",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#c9c5ca",
        "secondary-container": "#ffca58",
        "tertiary-container": "#fcfcfa",
        "on-tertiary-fixed-variant": "#464248",
        "surface-container-lowest": "#101112",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#262427",
        "surface-variant": "#403c43",
        "inverse-on-surface": "#343136",
        "on-surface": "#fcfcfa",
        "on-primary-fixed": "#101112",
        "tertiary": "#fcfcfa",
        "secondary": "#ffca58",
        "tertiary-fixed": "#fcfcfa",
        "surface-container-highest": "#403c43",
        "secondary-fixed-dim": "#ffca58",
        "on-secondary-fixed": "#262427",
        "primary-container": "#49cae4",
        "background": "#262427",
        "surface-bright": "#4a454d",
        "surface-dim": "#1c1b1d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "container-max": "1200px",
        "unit": "8px",
      },
      fontFamily: {
        "headline-md": ["var(--font-bricolage)"],
        "label-caps": ["var(--font-jetbrains)"],
        "body-md": ["var(--font-hanken)"],
        "display-lg": ["var(--font-bricolage)"],
        "technical-sm": ["var(--font-jetbrains)"],
        "body-lg": ["var(--font-hanken)"],
        "display-lg-mobile": ["var(--font-bricolage)"],
      },
      fontSize: {
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "label-caps": [
          "11px",
          { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" },
        ],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": [
          "64px",
          {
            lineHeight: "72px",
            letterSpacing: "-0.02em",
            fontWeight: "800",
          },
        ],
        "technical-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg-mobile": [
          "36px",
          {
            lineHeight: "44px",
            letterSpacing: "-0.02em",
            fontWeight: "800",
          },
        ],
      },
    },
  },
  plugins: [],
};
export default config;
